### PR TITLE
merge root and subpath params

### PR DESCRIPTION
**Pull request by FalcoSuessgott**

### CODE REVIEW

**Comment by FalcoSuessgott** [comment]
# [Codecov](https://codecov.io/gh/FalcoSuessgott/vkv/pull/6?src=pr&el=h1&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=None) Report
> Merging [#6](https://codecov.io/gh/FalcoSuessgott/vkv/pull/6?src=pr&el=desc&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=None) (450e13d) into [master](https://codecov.io/gh/FalcoSuessgott/vkv/commit/93ae57948fc991a8232ca866afc51317c6067048?el=desc&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=None) (93ae579) will **increase** coverage by `0.97%`.
> The diff coverage is `75.00%`.

[Impacted file tree graph](https://codecov.io/gh/FalcoSuessgott/vkv/pull/6?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=None)

```diff
@@            Coverage Diff             @@
##           master       #6      +/-   ##
==========================================
+ Coverage   63.56%   64.54%   +0.97%     
==========================================
  Files           4        4              
  Lines         247      251       +4     
==========================================
+ Hits          157      162       +5     
+ Misses         71       70       -1     
  Partials       19       19              
```


| [Impacted Files](https://codecov.io/gh/FalcoSuessgott/vkv/pull/6?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=None) | Coverage Δ | |
|---|---|---|
| [cmd/root.go](https://codecov.io/gh/FalcoSuessgott/vkv/pull/6/diff?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=None#diff-Y21kL3Jvb3QuZ28=) | `27.27% <33.33%> (+0.48%)` | :arrow_up: |
| [pkg/utils/utils.go](https://codecov.io/gh/FalcoSuessgott/vkv/pull/6/diff?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=None#diff-cGtnL3V0aWxzL3V0aWxzLmdv) | `86.20% <100.00%> (+2.87%)` | :arrow_up: |

------

[Continue to review full report at Codecov](https://codecov.io/gh/FalcoSuessgott/vkv/pull/6?src=pr&el=continue&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=None).
> **Legend** - [Click here to learn more](https://docs.codecov.io/docs/codecov-delta?utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=None)
> `Δ = absolute <relative> (impact)`, `ø = not affected`, `? = missing data`
> Powered by [Codecov](https://codecov.io/gh/FalcoSuessgott/vkv/pull/6?src=pr&el=footer&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=None). Last update [93ae579...450e13d](https://codecov.io/gh/FalcoSuessgott/vkv/pull/6?src=pr&el=lastupdated&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=None). Read the [comment docs](https://docs.codecov.io/docs/pull-request-comments?utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=None).

**Comment by krot4u** [comment]
Hi Falco! Thanx for your OpenSource!
After you merged root and subpath - I think now it is creating a wrong URL for request
When I run `.\vkv.exe -p /root/sub1/sub2/sub3`
I getting error :

> Code: 403. Errors:
> * 1 error occurred:
>         * permission denied
>  https://sog-vault.avp.ru:8200/v1/metadata/root/sub1/sub2/sub3?list=true

The problem is - the metadata part should be in between <root> and <sub> like so:
https://sog-vault.avp.ru:8200/v1/root/metadata/sub1/sub2/sub3?list=true
according to https://www.vaultproject.io/api/secret/kv/kv-v2#list-secrets

**Comment by FalcoSuessgott** [comment]
Hi @krot4u thanks I will look into it very soon!

**Comment by krot4u** [comment]
At leaet windows version is affected.
Linux version working fine.

**Comment by FalcoSuessgott** [comment]
I think if you remove the leading `\` it is working fine, can you try this?:

```bash
 .\vkv.exe -p root/sub1/sub2/sub3
```

**Comment by FalcoSuessgott** [comment]
@krot4u  [v0.0.5](https://github.com/FalcoSuessgott/vkv/releases) should work with a leading `/` :)

**Comment by krot4u** [comment]
Nope... not working

**Comment by krot4u** [comment]
Screenshot 2022-02-24 at 17 15 00

**Comment by krot4u** [comment]
InkedScreenshot 2022-02-24 at 17 15 00_LI

**Comment by krot4u** [comment]
InkedScreenshot 2022-02-24 at 17 18 05_LI

**Comment by krot4u** [comment]
Further debugging:
 .\vkv.exe -p osmp-deploy/IT-Secrets
ListRecursive ================ rootPath osmp-deploy, subPath IT-Secrets.
ReadSecrets ================ rootPath osmp-deploy, subPath IT-Secrets\Azure.
Read ================ osmp-deploy/data/IT-Secrets\Azure
error executing root command: no secrets found.

**Comment by FalcoSuessgott** [comment]
Ah okay this is due to how `/` are handled on windows, he is replacing `/` with `\`, let me see what I can do

**Pull request merged**
